# File: clickhouse-single.yaml
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: single
spec:
  configuration:
    clusters:
      - name: clickhouse
    users:
      # printf 'mozox-password' | sha256sum
      mozox/password_sha256_hex: ea3e0ba4c196be92523629d14b345d054588f5df9cfb338369e6a15a3b562fa9
      # or plaintext
      mozox/password: '12345678'
      mozox/networks/ip:
        - 0.0.0.0/0