---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: single
spec:
  configuration:
    clusters:
      - name: clickhouse
    users:
      default/password: '12345678'
      default/networks/ip:
        - 0.0.0.0/0