apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulsardata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar:4.0.2
          command: ["bin/pulsar", "standalone"]
          ports:
            - containerPort: 6650
            - containerPort: 8080
          volumeMounts:
            - name: pulsardata
              mountPath: /pulsar/data
          tty: true
      volumes:
        - name: pulsardata
          persistentVolumeClaim:
            claimName: pulsardata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pulsar-service
spec:
  type: LoadBalancer
  selector:
    app: pulsar
  ports:
    - name: broker
      port: 6650
      targetPort: 6650
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP